//
//  STPPaymentHandler.swift
//  StripeiOS
//
//  Created by Cameron Sabol on 5/10/19.
//  Copyright © 2019 Stripe, Inc. All rights reserved.
//

import Foundation
import PassKit

/// `STPPaymentHandlerActionStatus` represents the possible outcomes of requesting an action by `STPPaymentHandler`. An action could be confirming and/or handling the next action for a PaymentIntent.
@objc public enum STPPaymentHandlerActionStatus: Int {
  /// The action succeeded.
  case succeeded
  /// The action was cancelled by the cardholder/user.
  case canceled
  /// The action failed. See the error code for more details.
  case failed
}

/// Error codes generated by `STPPaymentHandler`
@objc public enum STPPaymentHandlerErrorCode: Int {
  /// Indicates that the action requires an authentication method not recognized or supported by the SDK.
  @objc(STPPaymentHandlerUnsupportedAuthenticationErrorCode)
  case unsupportedAuthenticationErrorCode

  /// Attach a payment method to the PaymentIntent or SetupIntent before using `STPPaymentHandler`.
  @objc(STPPaymentHandlerRequiresPaymentMethodErrorCode)
  case requiresPaymentMethodErrorCode

  /// The PaymentIntent or SetupIntent status cannot be resolved by `STPPaymentHandler`.
  @objc(STPPaymentHandlerIntentStatusErrorCode)
  case intentStatusErrorCode

  /// The action timed out.
  @objc(STPPaymentHandlerTimedOutErrorCode)
  case timedOutErrorCode

  /// The transaction did not authenticate (e.g. user entered the wrong code).
  @objc(STPPaymentHandlerNotAuthenticatedErrorCode)
  case notAuthenticatedErrorCode

  /// `STPPaymentHandler` does not support concurrent actions.
  @objc(STPPaymentHandlerNoConcurrentActionsErrorCode)
  case noConcurrentActionsErrorCode

  /// Payment requires a valid `STPAuthenticationContext`.  Make sure your presentingViewController isn't already presenting.
  @objc(STPPaymentHandlerRequiresAuthenticationContextErrorCode)
  case requiresAuthenticationContextErrorCode

  /// There was an error confirming the Intent.
  /// Inspect the `paymentIntent.lastPaymentError` or `setupIntent.lastSetupError` property.
  @objc(STPPaymentHandlerPaymentErrorCode)
  case paymentErrorCode

  /// The provided PaymentIntent of SetupIntent client secret does not match the expected pattern for client secrets.
  /// Make sure that your server is returning the correct value and that is being passed to `STPPaymentHandler`.
  @objc(STPPaymentHandlerInvalidClientSecret)
  case invalidClientSecret
}

/// Completion block typedef for use in `STPPaymentHandler` methods for Payment Intents.
public typealias STPPaymentHandlerActionPaymentIntentCompletionBlock = (
  STPPaymentHandlerActionStatus, STPPaymentIntent?, NSError?
) -> Void
/// Completion block typedef for use in `STPPaymentHandler` methods for Setup Intents.
public typealias STPPaymentHandlerActionSetupIntentCompletionBlock = (
  STPPaymentHandlerActionStatus, STPSetupIntent?, NSError?
) -> Void
